name: Actions on PR
on:
  - pull_request
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
    - name: Terraform fmt
      run: terraform fmt
      continue-on-error: true
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Render terraform docs inside the USAGE.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v0.6.1
      with:
        tf_docs_working_dir: .
        tf_docs_output_file: USAGE.md
        tf_docs_content_type: document
        tf_docs_output_method: replace
        tf_docs_git_push: 'true'
