name: Minimal tests
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test-fast.yaml"
  push:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*"
      - "!.github/workflows/test-fast.yaml"
jobs:
  minimal:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: "examples/minimal"
      OS_AUTH_URL: ${{ secrets.OS_AUTH_URL }}
      OS_IDENTITY_API_VERSION:  ${{ secrets.OS_IDENTITY_API_VERSION }}
      OS_PASSWORD:  ${{ secrets.OS_PASSWORD }}
      OS_PROJECT_ID:  ${{ secrets.OS_PROJECT_ID }}
      OS_PROJECT_NAME:  ${{ secrets.OS_PROJECT_NAME }}
      OS_REGION_NAME:  ${{ secrets.OS_REGION_NAME }}
      OS_USERNAME:  ${{ secrets.OS_USERNAME }}
      OS_USER_DOMAIN_NAME:  ${{ secrets.OS_USER_DOMAIN_NAME }}
      TF_VAR_DNS_SERVERS:  ${{ secrets.TF_VAR_DNS_SERVERS }}
    environment: nova
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0
    - name: Set up ssh-agent
      run: ssh-agent  -s |grep -E '^(SSH_AUTH_SOCK|SSH_AGENT_PID)'|cut -f1 -d ';' >> $GITHUB_ENV
    - name: Create and add key to ssh-agent
      run: ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa && ssh-add
    - name: Using local module source
      run: sed -i "s+remche/rke2/openstack+./../..+" main.tf
    - name: Terraform init
      run: terraform init
      working-directory: ${{ env.WORKING_DIR }}
    - name: Terraform apply
      run: terraform apply -auto-approve
      working-directory: ${{ env.WORKING_DIR }}
    - name: Terraform destroy
      if: ${{ always() }}
      run: terraform destroy -auto-approve
      working-directory: ${{ env.WORKING_DIR }}
